// Mocks generated by Mockito 5.0.5 from annotations
// in t_truck_app/test/features/data/repository/invoice_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:t_truck_app/features/data/external/adapters/i_invoice_external.dart'
    as _i2;
import 'package:t_truck_app/features/domain/entites/invoice.dart' as _i4;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [IInvoiceExternal].
///
/// See the documentation for Mockito's code generation for more information.
class MockIInvoiceExternal extends _i1.Mock implements _i2.IInvoiceExternal {
  MockIInvoiceExternal() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Invoice>> list() =>
      (super.noSuchMethod(Invocation.method(#list, []),
              returnValue: Future<List<_i4.Invoice>>.value(<_i4.Invoice>[]))
          as _i3.Future<List<_i4.Invoice>>);
}
