// Mocks generated by Mockito 5.0.5 from annotations
// in t_truck_app/test/features/data/repository/order_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:t_truck_app/features/data/external/adapters/i_order_external.dart'
    as _i2;
import 'package:t_truck_app/features/domain/entites/order_entity.dart' as _i4;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [IOrderExternal].
///
/// See the documentation for Mockito's code generation for more information.
class MockIOrderExternal extends _i1.Mock implements _i2.IOrderExternal {
  MockIOrderExternal() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.OrderEntity>> list() => (super.noSuchMethod(
          Invocation.method(#list, []),
          returnValue: Future<List<_i4.OrderEntity>>.value(<_i4.OrderEntity>[]))
      as _i3.Future<List<_i4.OrderEntity>>);
}
